// pms-staff/src/pages/todos/todos.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { get } from '@/api/request'

interface TodoItem {
  id: number
  code: string
  title: string
  type: string
  status: string
}

const workOrders = ref<TodoItem[]>([])
const inspectionTasks = ref<TodoItem[]>([])
const loading = ref(true)

onMounted(async () => {
  try {
    const res = await get<{ workOrders: TodoItem[]; inspectionTasks: TodoItem[] }>('/api/mp/my-todos')
    if (res.success && res.data) {
      workOrders.value = res.data.workOrders || []
      inspectionTasks.value = res.data.inspectionTasks || []
    }
  } catch {
    uni.showToast({ title: '加载失败', icon: 'none' })
  } finally {
    loading.value = false
  }
})

function goWorkOrderDetail(id: number) {
  uni.navigateTo({ url: `/pages/work-orders/detail?id=${id}` })
}
</script>

<template>
  <view class="page">
    <view v-if="loading" class="loading">加载中…</view>
    <view v-else>
      <view class="section" v-if="workOrders.length > 0">
        <view class="section-title">待处理工单</view>
        <view
          v-for="item in workOrders"
          :key="'wo-' + item.id"
          class="card"
          @click="goWorkOrderDetail(item.id)"
        >
          <view class="title">{{ item.title }}</view>
          <view class="meta">{{ item.code }} · {{ item.status }}</view>
        </view>
      </view>
      <view class="section" v-if="inspectionTasks.length > 0">
        <view class="section-title">巡检任务</view>
        <view v-for="item in inspectionTasks" :key="'it-' + item.id" class="card">
          <view class="title">{{ item.code || item.title }}</view>
          <view class="meta">{{ item.status }}</view>
        </view>
      </view>
      <view v-if="!loading && workOrders.length === 0 && inspectionTasks.length === 0" class="empty">
        暂无待办
      </view>
    </view>
  </view>
</template>

<style lang="scss" scoped>
.page {
  padding: 24rpx;
  min-height: 100vh;
  box-sizing: border-box;
}

.loading,
.empty {
  text-align: center;
  padding: 100rpx 40rpx;
  color: $pms-text-muted;
  font-size: 28rpx;
}

.section {
  margin-bottom: 40rpx;
}

.section-title {
  @include pms-section-title;
}

.card {
  @include pms-card;
  @include pms-tap;
  padding: 32rpx;
  margin-bottom: 24rpx;
}

.title {
  font-size: 30rpx;
  font-weight: 600;
  color: $pms-text;
  margin-bottom: 12rpx;
}

.meta {
  font-size: 24rpx;
  color: $pms-text-muted;
}
</style>

// pms-web/src/app/m/staff/(main)/todos/page.tsx
'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { MStaffSubPageBar } from '@/components/m/MStaffSubPageBar'

type TodoItem = {
  id: number
  code: string
  title: string
  type: string
  status: string
}

export default function StaffTodosPage() {
  const [workOrders, setWorkOrders] = useState<TodoItem[]>([])
  const [inspectionTasks, setInspectionTasks] = useState<TodoItem[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    void (async () => {
      try {
        const r = await fetch('/api/mp/my-todos', { credentials: 'include' })
        const j = await r.json()
        if (j.success && j.data) {
          setWorkOrders(j.data.workOrders ?? [])
          setInspectionTasks(j.data.inspectionTasks ?? [])
        }
      } catch {
        setWorkOrders([])
        setInspectionTasks([])
      } finally {
        setLoading(false)
      }
    })()
  }, [])

  return (
    <div className="p-4 max-w-lg mx-auto pb-2">
      <MStaffSubPageBar title="待办" />
      {loading ? (
        <p className="text-sm text-slate-500 text-center py-8">加载中…</p>
      ) : (
        <>
          {workOrders.length > 0 && (
            <section className="mb-6">
              <h2 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                待处理工单
              </h2>
              <ul className="space-y-2">
                {workOrders.map((item) => (
                  <li key={`wo-${item.id}`}>
                    <Link
                      href={`/m/staff/work-orders/${item.id}`}
                      className="block rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-4 active:scale-[0.99] transition-transform"
                    >
                      <p className="font-medium line-clamp-2">{item.title}</p>
                      <p className="text-xs text-slate-500 mt-1">
                        {item.code} · {item.status}
                      </p>
                    </Link>
                  </li>
                ))}
              </ul>
            </section>
          )}
          {inspectionTasks.length > 0 && (
            <section className="mb-6">
              <h2 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                巡检任务
              </h2>
              <ul className="space-y-2">
                {inspectionTasks.map((item) => (
                  <li
                    key={`it-${item.id}`}
                    className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-4"
                  >
                    <p className="font-medium">{item.code || item.title}</p>
                    <p className="text-xs text-slate-500 mt-1">{item.status}</p>
                  </li>
                ))}
              </ul>
            </section>
          )}
          {workOrders.length === 0 && inspectionTasks.length === 0 && (
            <p className="text-sm text-slate-500 text-center py-12">暂无待办</p>
          )}
        </>
      )}
    </div>
  )
}
